config/routes.rb
Twitterick::Application.routes.draw do
  devise_for :users
  root :to => "poems#index"  
  resources :poems do 
  	post :like 
  end
  get "/twitter_handles/new" => "twitter_handles#new"
  post "/twitter_handles" => "twitter_handles#create"
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user 
	belongs_to :poem
end

app/models/poem.rb
class Poem < ActiveRecord::Base
	has_many :poem_tweets 
	has_many :tweets, through: :poem_tweets
	has_many :likes 
	has_many :users, :through => :likes
end

app/models/poem_tweet.rb
class PoemTweet < ActiveRecord::Base
	belongs_to :tweet
	belongs_to :poem
end

app/models/tweet.rb
require 'syllable_module'
require 'rhyme_module'

class TweetValidation < ActiveModel::Validator
	def validate(tweet)
		if tweet.text.include?("@")
			tweet.errors[:base] << "This tweet refers to another user"
		end
		
		if tweet.text.include?("#")
			tweet.errors[:base] << "This tweet includes a hashtag"
		end
		
		if tweet.text.include?("http://")
			tweet.errors[:base] << "This tweet includes a url"
		end

		if tweet.text.include?("https://")
			tweet.errors[:base] << "This tweet includes a url"
		end

		if tweet.text.syllable_count < 4 
			tweet.errors[:base] << "This tweet has less than four syllables"	
		end	

		if tweet.text.syllable_count > 12 
			tweet.errors[:base] << "This tweet has too many syllables"	
		end			
	end

end 

class Tweet < ActiveRecord::Base
	belongs_to :twitter_handle
	has_many :poem_tweets 
	has_many :poems, through: :poem_tweets

	validates :tweet_status_num, :twitter_handle_id, :tweet_status_url, presence: true
	validates :tweet_status_num, uniqueness: true
	validates_with TweetValidation
	after_create :set_num_syllables
	after_create :set_num_rhymes

	private

	def set_num_syllables
		self.num_syllables = self.text.syllable_count
		self.save
	end

	def set_num_rhymes
		self.num_rhymes = RhymingWords.get_num_rhymes(self.last_word)
		self.save
	end
end

app/models/twitter_handle.rb
require 'twitter_api'
class TwitterHandleValidation < ActiveModel::Validator
	include TwitterApi
	def validate(twitter_handle)
		if (twitter_handle.handle[0] == "@")
			twitter_handle.handle = twitter_handle.handle[1..twitter_handle.handle.length]
		end
		twitter_handle.handle = twitter_handle.handle.downcase
		if th = check_twitter_handle(twitter_handle.handle)
			twitter_handle.name = th.name
		else
			twitter_handle.errors[:base] << "This handle is not a valid Twitter handle"
			return nil
		end
	end
end

class TwitterHandle < ActiveRecord::Base

	has_many :tweets 
	belongs_to :user 

	validates_with TwitterHandleValidation
	validates :handle, uniqueness: true, presence: true 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 
         :twitter_handle_id

  has_many :twitter_handles
  
  has_many :likes

  has_many :poems, :through => :likes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/poems_controller.rb
require 'twitter_api'
require 'poem_module'
require 'rhyme_module'

class PoemsController < ApplicationController
	include TwitterApi
	include PoemConstructor

	def index
		@coder = HTMLEntities.new
		@poem = Poem.all.sample
		@poem_tweets = @poem.poem_tweets.order(:line_num)
		if (current_user)
			@liked = Like.where(poem: @poem, user: current_user).first
		end
	end

	def create
		if (poem = construct_poem(TwitterHandle.find(params[:id])))
			@poem = poem.poem_tweets.order(:line_num)
			redirect_to poem_path(poem)
		else
			redirect_to new_poem_path, alert: "Sorry! Unable to create a poem with the Twitter handle submitted."
		end
	end 
	
	def new
		@twitter_handles = []
		twitter_handles = TwitterHandle.all.order(:name)
		twitter_handles.each do |th|
			if th.tweets.count > 10
				@twitter_handles.push(th)
			end
		end
	end

	def show 
		@coder = HTMLEntities.new
		@poem = Poem.find(params[:id])
		@tweets = @poem.poem_tweets.order(:line_num)
		if (current_user)
			@liked = Like.where(poem: @poem, user: current_user).first
		end
	end

	def like 
		if params[:like] == "true"
			Poem.find(params[:poem_id]).users << current_user
		else
			like = Like.where(user_id: current_user.id, poem_id: params[:poem_id]).first
			like.destroy 
		end
		redirect_to poem_path(params[:poem_id])
	end

	private

	def poem_params
		params.require(:poem)
	end

	def twitter_handle_params
		params.require(:twitter_handle).permit(:handle)
	end

end

app/controllers/twitter_handles_controller.rb
class TwitterHandlesController < ApplicationController
	def new
	end

	def create		
		twitter_handle = TwitterHandle.create(twitter_handle_params)
		if twitter_handle.id
			redirect_to root_url, notice: "Thanks for submitting a new Twitter handle. Be sure to check back to see it featured in a poem."
		else
			redirect_to twitter_handles_new_path, alert: "Sorry! Either this handle has already been submitted or is not recognized by Twitter."
		end
	end
	def twitter_handle_params
		params.require(:twitter_handle).permit(:handle)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Twitterick</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => false %>
	<%= csrf_meta_tags %>
	<link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
	<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
</head>
<body>
	<div class="navbar navbar-default" role="navigation">
	<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="title-link" href="/">Twitterick</a>
			</div>
			<div class="navbar-collapse collapse">
				<% if user_signed_in? %>		
				<form class="navbar-form navbar-right" role="form" action="/users/sign_out" method="post">
					<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
					<input type="hidden" name="_method" value="delete">
					<button type="submit" class="btn btn-link">Sign out</button>
				</form>
				<ul class="nav navbar-nav navbar-right">
					<li><a class="email-link" href="/users/edit"><%= current_user.email %></a></li>
				</ul>
				<% else %>
				<ul class="nav navbar-nav navbar-right">
					<li><a href="/users/sign_in">Sign in</a></li>
					<li><a href="/users/sign_up">Sign up</a></li>
				</ul>
				</div>
				<% end %>
			</div>
		</div>
	</div>
	<div class="container">
		<% if notice %>
		<div class="alert alert-success alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden=" true">&times;</button>
			<%= notice %>
		</div>
		<% end %>
		<% if alert %>
		<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden=" true">&times;</button>
			<%= alert %>
		</div>
		<% end %>

		<%= yield %>
	</div>
	<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
		<div class="container">
		   	<small>Made by Isaac Torres &amp; Colleen Joyce</small>
		</div>
	</nav>
</body>
</html>

app/views/poems/index.html.erb
<div class="display-random-poem">
	<ul>
	<% @poem_tweets.each do |poem_tweet| %>
		<li>
		<a class="poem-line" href="<%= poem_tweet.tweet.tweet_status_url %>">
		<%= @coder.decode(poem_tweet.tweet.text) %>
		</a>
		<h6><a class="twitter-handle-link" href="https://twitter.com/<%= poem_tweet.tweet.twitter_handle.handle %>"><%= '@' + poem_tweet.tweet.twitter_handle.handle %></a></h6>
		</li>
	<% end %>
	</ul>
	<br>
	<% if user_signed_in? %>	
	<% if @liked %>
		<form class="dislike-button" action=<%=poem_like_path(@poem.id)%> method="post">
			<input type="hidden" name="like" value="false">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<button type="submit" class="like-btn"><i class="fa fa-heart-o fa-lg"></i></button>
		</form>
	<% else %>
		<form class="like-button" action=<%=poem_like_path(@poem.id)%> method="post">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
			<input type="hidden" name="like" value="true">
			<button type="submit" class="like-btn" ><i class="fa fa-heart fa-lg"></i></button>	
		</form>
	<% end %>
	<% end %>
	<br>
	<a href="/poems/new" class="create-poem-link">Create a poem of your own!</a>
</div>

app/views/poems/new.html.erb
<div class="jumbotron">
	<h1>Create a poem</h1>
	<div class="words">
		<p>Choose from our list of Twitter personalities</p>
	</div>
	<form action="/poems" method="POST">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		<div class="row">
		<select class="input-lg col-md-offset-3 col-md-4" name="id">
			<% @twitter_handles.each do |handle| %>
				<option value="<%= handle.id %>"><%= handle.name %></option>
			<% end %>
		</select>
		<input id="handles-select-submit" class="btn btn-default btn-lg col-md-3" type="submit"> 
</div>

<div class="link-below">
	<a class="link-below" href="/twitter_handles/new">...or submit one of your own.</a>
</div>

app/views/poems/show.html.erb
<div class="jumbotron">
<div class="jumbotron-content">
	<% @tweets.each do |tweet| %>
		<p>
			<a class="poem-line" href="<%= tweet.tweet.tweet_status_url %>">
			<%= @coder.decode(tweet.tweet.text) %></a>
			<h6><a class="twitter-handle-link" href="https://twitter.com/<%= tweet.tweet.twitter_handle.handle %>"><%= "@" + tweet.tweet.twitter_handle.handle %></a></h6>
		</p>
	<% end %>
	<a class="again" href="/poems/new">Again!</a>
	<% if user_signed_in? %>	
		<% if @liked %>
			<form class="dislike-button" action=<%=poem_like_path(@poem.id)%> method="post">
				<input type="hidden" name="like" value="false">
				<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
				<button type="submit" class="like-btn"><i class="fa fa-heart-o fa-lg"></i></button>
			</form>
		<% else %>
			<form class="like-button" action=<%=poem_like_path(@poem.id)%> method="post">
				<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
				<input type="hidden" name="like" value="true">
				<!-- <button type="submit" class="like-btn">Like</button> -->
				<button type="submit" class="like-btn"><i class="fa fa-heart fa-lg"></i></button>	
			</form>
		<% end %>
	<% end %>
	</div>
</div>

app/views/twitter_handles/new.html.erb
<style>
#submit-twitter-handle .form-control{
	margin-top:0;
	margin-bottom:0;
	width:200px;}

#submit-twitter-handle .btn-default{
	margin-top:0;}
</style>

<div class="jumbotron">
	<h1>Submit a Twitter handle</h1>
	<form action="/twitter_handles" method="POST">
		<div id="submit-twitter-handle">
			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> 
			<input class="input-lg" required="true" type="text" name="twitter_handle[handle]" placeholder="@username">
			<input class="btn btn-default btn-lg" type="submit">
		</div>
	</form>
</div>